def testlevel():
    print("Let's start with something simple!")
    print("Enter the name of a person")
    nameofpersontest = str(input())
    print("Enter an adjective")
    adjectivetest = str(input())
    print("Enter a plural noun")
    pluralnountest = str(input())
    print("Enter an adjective")
    adjective2test = str(input())
    print("Here is the result:")
    print("Greg, Rowley, Manny, and "+nameofpersontest+" might seem like the most "+adjectivetest+" of "+pluralnountest+", but in real life, they are actually totally "+adjective2test+"!")

def level1():
    print("Greg's journal: New year's resolutions")
    print("Enter a plural noun")
    pluralnoun11 = str(input())
    print("Enter a noun")
    noun11 = str(input())
    print("Enter a verb ending in 'ing'")
    verbendingwithing11 = str(input())
    print("Enter a number")
    number1 = str(input())
    print("Enter a place")
    place11 = str(input())
    print("Enter a plural noun")
    pluralnoun12 = str(input())
    print("Enter a noun")
    noun12 = str(input())
    print("Enter a type of food")
    typeoffood1 = str(input())
    print("Enter a color")
    color1 = str(input())
    print("Enter an adverb")
    adverb1 = str(input())
    print("Enter a noun")
    noun13 = str(input())
    print("Enter an article of clothing")
    articleofclothing1 = str(input())
    print("Enter a noun")
    noun14 = str(input())
    print("Enter a place")
    place12 = str(input())
    print("Enter a verb ending with 'ing'")
    verbendingwithing12 = str((input))
    print("Here is the result:")
    print("I'm pretty much one of the best "+pluralnoun11+" I know aldready,so I've never made any New Year's resolutions. Just to know what it's like, though, I'm giving it a try this "+noun11+" Here's what I have so far:\n->Start "+verbendingwithing11+" my teeth at least "+number1+" times a month. Otherwise, I'm afraid that I'll be the only kid in (the) "+place11+" who wears dentures!\n->Send thank you "+pluralnoun12+" right away after I get a/an "+noun12+" I think if I'd remembered to write them after my birthday, I would've gotten more presents for christmas.\n->Try a piece of "+typeoffood1+" or some other "+color1+" vegetable before the end of the year, even though I'm pretty sure vagetables aren't "+adverb1+" meant to be eaten.\n->Pitch in more around the "+noun13+". Usually, I just drop my "+articleofclothing1+" and backpack on the "+noun14+" as soon as I get home from (the) "+place12+". From now on, I'll try "+verbendingwithing12+" them right to Mom so it's easier for her to put them away.")

def level2():
    print("A message from Mr.Winsky")
    print("Enter a plural noun")
    pluralnoun21 = str(input())
    print("Enter an adjective")
    adjective21 = str(input())
    print("Enter a noun")
    noun21 = str(input())
    print("Enter a plural noun")
    pluralnoun22 = str(input())
    print("Enter a place")
    place21 = str(input())
    print("Enter a noun")
    noun22 = str(input())
    print("Enter an adjective")
    adjective22 = str(input())
    print("Enter an adverb")
    adverb21 = str(input())
    print("Enter a type of liquid")
    typeofliquid21 = str(input())
    print("Enter an adjective")
    adjective23 = str(input())
    print("Verb ending with 'ing'")
    verbendingwithing21 = str(input())
    print("Enter an adverb")
    adverb22 = str(input())
    print("Enter a plural noun")
    pluralnoun23 = str(input())
    print("Enter an adjective")
    adjective24 = str(input())
    print("Enter a noun")
    noun23 = str(input())
    print("Enter an adverb")
    adverb23 = str(input())
    print("Here's the result:")
    print("Attention, all Safety Patrols:\nRecently, one of your fellow "+pluralnoun21+", who I won't mention by name, thought it would be "+adjective21+" to chase a group of kindergartners with a worm on a/an "+noun21+". Not only did he terrorize the very "+pluralnoun22+" he was supposed to protect as they walked home from (the) "+place21+", but he also allowed the "+noun22+" to fall on another Patrol. Clearly, Greg Heffley's actions were "+adjective22+", which is why he was "+adverb21+" relieved of his duties and stripped of his morning "+typeofliquid21+" privileges. To prevent this "+adjective23+" incident from "+verbendingwithing21+" the reputation of all safety patrols, you must each take your job extra "+adverb22+" in the coming "+pluralnoun23+". I would like to put this incident behind us, but before we do, I'd like to thank Rowley Jefferson for showing dignity under"+adjective24+" suspicion. Let his "+noun23+" be an example to us all.\n"+adverb23+",\nMr. Winsky")

def madlibs():
    print("Choose a level: test (t), level 1 (1), level 2 (2), level 3 (3) or level 4 (4)")
    level = input()
    print("Here are a few quick rules:\n-> An ADJECTIVE describes something or somebody. \n-> An ADVERB tells how something is done. It modifies a verb and usually ends with 'ly'. \n-> A NOUN is the name of a person, place, or thing. \n-> A VERB is an action word. ")
    if level == "t":
        testlevel()
        madlibs()
    elif level == "1":
        level1()
        madlibs()
    elif level == "2":
        level2()
        madlibs()
    else:
        print("That's not correct, let's try again")
        madlibs()

def tryexceptmadlibs():
    try:
        madlibs()
    except Exception as e:
        print("Couldn't continue reason: "+e)
    madlibs()

print("Welcome to the wimpy kid madlibs simulator")
tryexceptmadlibs()